import { Maven_Pro, Nunito_Sans, Galad } from 'next/font/google';
import './globals.css'
import Navbar from './ui/navbar'
import Footer from './ui/footer';

const nunito_Sans = Nunito_Sans({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito_Sans.className}>
        <main className="min-h-screen justify-between bg-white max-w-full">
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  )
}
